# config/meta.yml

meta_product_name: "Gestuno"
meta_title: "Gestuno — Find Your Sign-Language Interpreter"
meta_description: "Instantly and conveniently connecting deaf people and sign-language users with professionally certified interpreters."
meta_image: "https://res.cloudinary.com/lionelrowe/image/upload/v1544093972/cover_o4e2nn.png"                       # should exist in `app/assets/images/`
twitter_account: "@gestunoapp"   # required for Twitter Cards
